Fix search in admin
naboj-org/bullet pull request #964
Opened 2024-10-02 09:29 UTC by krtko1

2024-10-02 09:58 UTC, gardenerik requested changes

2024-10-02 09:58 UTC, gardenerik commented on bullet/bullet_admin/views/__init__.py
> +                        print(type(field).__name__)
```suggestion
```

2024-10-02 09:59 UTC, krtko1 commented on bullet/bullet_admin/views/__init__.py
> +                        print(type(field).__name__)
joj

2024-10-03 08:57 UTC, gardenerik approved these changes

2024-10-03 08:58 UTC, merged